.TH INCLUDE 3
.SH NAME
include \- include another chunk of a man page
.SH INCLUDED BIT
.nr zY 1
.so man3/included.3
.SH HYPHENS
This isn't a hyphen\*(--just a long dash\*(--and \h'-1' also isn't, nor
should we warn about `\-' or \-a, but -a
and `-' (nope, that's fine) are bad news.  So is
--foo and
(--bar)
"--baz"
and '--foo'.
.SH SEE ALSO
included(3)
