# Copyright 2010 Niels Thykier
#  - based on the work Richard Braakman and Christian
#    Schwarz (copyrighted 1998).
#
# This manual page is free software.  It is distributed under the
# terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# This manual page is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this manual page; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301
# USA
#

=head1 NAME

lintian-info - give detailed information about Lintian's error tags

=head1 SYNOPSIS

B<lintian-info> [I<log-file>...]

B<lintian-info> B<--tags> I<tag> ...

=head1 DESCRIPTION

The B<lintian-info> command parses the output of the B<lintian>
command and gives verbose information about the listed Lintian error
tags, parses a Lintian override file and gives verbose information
about the tags included, or (if given the B<-t> or B<--tags> option)
explains a given tag or tags.

If no log-file is specified on the command line, this command expects
its input on stdin. Thus, the output of B<lintian> can either be piped
through B<lintian-info> or a log file produced by B<lintian> can be
processed with this command.  (Note, though, that the B<lintian>
command has a command line option B<-i> to display the same results as
B<lintian-info>, so you will not normally need to pipe the output of
B<lintian> into this command.)


=head1 OPTIONS

=over 4

=item B<-a>, B<--annotate>

Read from standard input or any files specified on the command line
and search the input for lines formatted like Lintian override
entries.  For each one that was found, display verbose information
about that tag.

=item B<-h>, B<--help>

Display usage information and exit.

=item B<--include-dir> dir

Use dir as an additional "Lintian root".  The directory is expected
have a similar layout to the LINTIAN_ROOT (if it exists), but does not
need to be a full self-contained root.

Unlike B<lintian>, B<lintian-info> will I<not> load any code from
these additional directories.

This option may appear more than once; each time adding an additional
directory.

=item B<--profile> prof

Use the severities from the vendor profile prof when displaying tags.
If the profile name does not contain a slash, the default profile for
than vendor is chosen.

If not specified, B<lintian-info> loads the best profile for the
current vendor.

Please Refer to the Lintian User Manual for the full documentation of
profiles.

=item B<-t>, B<--tags>

Rather than treating them as log file names, treat any command-line
options as tag names and display the descriptions of each tag.

=item B<--user-dirs>, B<--no-user-dirs>

By default, B<lintian> will check I<$HOME> and I</etc> for files
supplied by the user or the local sysadmin (e.g. profiles).  This
default can be disabled (and re-enabled) by using B<--no-user-dirs>
(and B<--user-dirs>, respectively).

These option can appear multiple times, in which case the of them
to appear determines the result.

=back

=head1 EXIT STATUS

If B<-t> or B<--tags> was given and one or more of the tags specified
were unknown, this command returns the exit code 1.  Otherwise, it
always returns with exit code 0.

=head1 SEE ALSO

L<lintian(1)>

=head1 AUTHORS

Niels Thykier <niels@thykier.net>

Richard Braakman <dark@xs4all.nl>

Christian Schwarz <schwarz@monet.m.isar.de>

=cut

