#!/bin/bash

update-alternatives --remove dummy /usr/bin/dummy-alternative

echo "Hit enter"
read

# neither of the following should be detected as postrm-unsafe-ldconfig
# intended, without quotes
   if [ "$1" = remove ]; then
       ldconfig
    fi
# reversed, many whitespace
if [ 'remove' = "$1" ]
then
 
 ldconfig
fi

[ "remove" ="$1" ] && ldconfig

update-rc.d bar remove

# Shouldn't provoke an error despite no invoke-rc.d.
echo "/etc/init.d/package stop to stop something"

# Shouldn't require a ucf dependency.  Unfortunately, right now that's
# just because postrm isn't checked, not because we ensure that the
# invocation is conditional.
if which ucf >/dev/null; then
    ucf --purge /etc/foo.conf
fi    
