#! /bin/sh

if [ "$1" = "configure" ]; then
        if [ -d /usr/doc -a ! -e /usr/doc/maintainer-scripts -a -d /usr/share/doc/maintainer-scripts ]; then
                ln -sf ../share/doc/maintainer-scripts /usr/doc/maintainer-scripts
        fi
fi

# valid
. /usr/share/lintian/shell || exit 0
# invalid
. /usr/share/lintian/shell foo

print "Hit enter to continue"
read

H[0]='this is a string'
echo ${H[0]}
echo "Index 0's length is ${#H[0]}"
echo "All of the array is: ${H[@]}"

install-info /usr/share/info/foo \
	--quiet \ # make it so
	--section foo

echo Please use update-rc.d or invoke-rc.d to set up blah blah.

wm-menu-config

chown root.root /usr/share/doc/maintainer-scripts/changelog
chown root:root /usr/share/doc/maintainer-scripts/changelog
