#!/bin/sh

update-rc.d foo remove
update-rc.d bar defaults

# Obsolete dpkg assertions.
dpkg --assert-support-predepends || exit 1
dpkg --assert-working-epoch || exit 1
dpkg --assert-long-filenames || exit 1
dpkg --assert-multi-conrep || exit 1
