#!/usr/bin/perl -w
# I used this to populate the %icon_cmap hash in checks/menu-format
# -- Joy, 2002-11-27, 2002-11-29

open C, "/usr/share/pixmaps/cmap.xpm" or die;
while (<C>) {
  if (/^.. . #(..)(..)(..)/) {
    my $red = $1;
    my $green = $2;
    my $blue = $3;
    $valid_colors{"#$red$green$blue"} = 1;
  }
}
close C;

print "   \'none\' => 1,\n";
foreach (sort keys %valid_colors) {
    print "   \'$_\' => 1,\n";
}

open R, "/etc/X11/rgb.txt" or die;
while (<R>) {
  if (/^\s*(\d+)\s+(\d+)\s+(\d+)\s+(\S+)/) { # ignore multi-word color names intentionally?
    my $hex = sprintf "%.2x%.2x%.2x", $1, $2, $3;
    my $name = lc $4;
    if (exists $valid_colors{"#$hex"}) {
      print "   \'$name\' => 1,\n";
    }
  }
}
close R;
