#!/bin/sh

set -e

# a previous version appended here but it breaks repeat runs
echo "E: runtests-calibration source: lintian-says-goodbye" > "$2"
echo "E: runtests-calibration source: lintian-says-goodbye" > "$3"
