#!/bin/sh

set -e

### BEGIN INIT INFO
# Provides: init.d-lsb-headers-local
# Required-Start:
# Required-Stop: $remote_fs
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Do nothing at all
# Description: The short description pretty much covers it.
### END INIT INFO

exec >/var/log/foo.log

. /lib/lsb/init-functions

case "$1" in
    start|stop|force-reload|restart|status|*)
	echo hello world!
    ;;
esac
