#!/bin/sh

set -e
WORKDIR="$ADTTMP/$(basename $0)"

export LINTIAN_TEST_INSTALLED=yes

rm -f runtests

debian/rules TEST_WORK_DIR="$WORKDIR" runtests onlyrun="suite:changes,suite:debs,suite:source,suite:tests"

rm -fr "${WORKDIR}"
