#!/bin/sh

# Good
echo $(py3versions -s)
echo $(py3versions -vs)
echo $(py3versions -sv)
echo $(py3versions -v)

# Bad
echo $(py3versions -i)
echo $(py3versions -vi)
echo $(py3versions --installed)
echo $(py3versions --verbose --installed)
