Tag: debian-control-has-dbgsym-package
Severity: error
Check: debian/control
See-Also: Bug#858117, https://wiki.debian.org/DebugPackage
Explanation: The <code>debian/control</code> file includes declaration of
 normally autogenerated -dbgsym package.
 .
 You should delete this package from <code>debian/control</code>
 and use autogeneration.
