Tag: debian-adds-svn-conflict-file
Severity: warning
Check: cruft
Renamed-From:
 diff-contains-svn-conflict-file
Explanation: The Debian diff or native package contains a file that looks like a
 Subversion conflict file. These are generated by Subversion when a
 conflict was detected while merging local changes with updates from a
 source repository. Use <code>svn resolved</code> to remove them and clear
 the Subversion conflict state after you have resolved the conflict.
