Tag: debian-control-has-obsolete-dbg-package
Severity: info
Check: debian/control
See-Also: https://wiki.debian.org/AutomaticDebugPackages
Explanation: The <code>debian/control</code> file includes declaration of
 -dbg package.
 .
 Debug package are now autogenerated avoiding waste of miror
 space.
 .
 Please note that -dbg should be dropped from control file
 and must not be transitioned to a dummy package depending
 on -dbgsym.
