Tag: debian-control-has-dbgsym-package
Severity: error
Check: debian/control
See-Also: #858117, https://wiki.debian.org/DebugPackage
Explanation: The <tt>debian/control</tt> file includes declaration of
 normally autogenerated -dbgsym package.
 .
 You should delete this package from <tt>debian/control</tt>
 and use autogeneration.
