#!/bin/sh
set -e

if [ remove = "$1" ]; then
    # Clean up the correct diversion from preinst.
    dpkg-divert --package scripts-diversions --remove --rename \
        --divert /usr/share/scripts/some-file.real \
        /usr/share/scripts/some-file

    # Clean up some other diversion that we didn't create.
    dpkg-divert --package scripts-diversions --remove --rename \
        /usr/share/scripts/old-file

    # Clean up a diversion we did create for a non-existent file.
    dpkg-divert --remove --package scripts-diversions --rename \
        --divert /usr/share/scripts/no-such-file.real \
        /usr/share/scripts/no-such-file
fi

#DEBHELPER#
