Document: generic-dh-make-2008
Title: Debian generic-dh-make-2008 Manual
Author: <insert document author here>
Abstract: This manual describes what generic-dh-make-2008 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/generic-dh-make-2008/generic-dh-make-2008.sgml.gz

Format: postscript
Files: /usr/share/doc/generic-dh-make-2008/generic-dh-make-2008.ps.gz

Format: text
Files: /usr/share/doc/generic-dh-make-2008/generic-dh-make-2008.text.gz

Format: HTML
Index: /usr/share/doc/generic-dh-make-2008/html/index.html
Files: /usr/share/doc/generic-dh-make-2008/html/*.html


