Tag: source-contains-svn-conflict-file
Severity: pedantic
Check: cruft
Explanation: The upstream source contains a file that looks like a Subversion
 conflict file. These are generated by Subversion when a conflict was
 detected while merging local changes with updates from a source
 repository. They're useful only while resolving the conflict and
 were probably included by accident. You may want to report this as an
 upstream bug.
