Tag: source-contains-autogenerated-gperf-data
Severity: pedantic
Check: cruft
Explanation: The following file is autogenerated by gperf
 .
 They are usually provided for the convenience of users. These files
 usually just take up space in the tarball.
 .
 Check if upstream also provides source-only tarballs that you can use as
 the upstream distribution instead. If not, you may want to ask upstream
 to provide source-only tarballs.
