Tag: source-contains-cvs-conflict-copy
Severity: pedantic
Check: cruft
Explanation: The upstream source contains a CVS conflict copy. These have file
 names like <code>.#file.version</code> and are generated by CVS when a
 conflict was detected when merging local changes with updates from a
 source repository. They're useful only while resolving the conflict and
 were probably included by accident. You may want to report this as an
 upstream bug.
