.\" Based on addpart.8 -- man page for addpart
.\" Copyright 2007 Karel Zak <kzak@redhat.com>
.\" Copyright 2007 Red Hat, Inc.
.\" May be distributed under the GNU General Public License
.TH PRIVATE-EXECUTABLE 8 "January 2015" "util-linux" "System Administration"
.SH NAME
private-executable \- part of the Lintian test suite
.SH DESCRIPTION
.B private-executable
is used internally and should not be invoked directly.
