#!/bin/sh

set -e

#
# Remove our generated locale if we are not upgrading or
# we are upgrading into a system with a libc provided
# C.UTF-8 (libc-bin >= 2.13)

if [ 'upgrade' != "$1" -o -d '/usr/lib/locale/C.UTF-8/' ] ; then
    rm -rf /var/lib/lintian/
fi

#DEBHELPER#
