#!/usr/bin/perl -w
# debfiles -- lintian collector script

# Copyright (C) 1999 by Joey Hess
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, you can find it on the World Wide
# Web at http://www.gnu.org/copyleft/gpl.html, or write to the Free
# Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
# MA 02110-1301, USA.

package Lintian::coll::debfiles;

use strict;
use warnings;


use lib "$ENV{'LINTIAN_ROOT'}/lib";
use Lintian::Util qw(copy_dir delete_dir fail);

sub collect {
my ($pkg, $type, $dir) = @_;

-e "$dir/unpacked" or fail 'debfiles invoked with wrong dir argument';

if ( -e "$dir/debfiles") {
    delete_dir ("$dir/debfiles")
        or fail('cannot rm old debfiles directory');
}

if ( -l "$dir/unpacked/debian" ) {
    require Cwd;
    my $target = Cwd::abs_path ("$dir/unpacked/debian");
    my $ud = "$dir/unpacked";
    fail ("cannot resolve debian directory symlink in $pkg: $!") unless $target;
    fail ("cannot resolve unpacked dir for $pkg: $!") unless $ud;
    # We need the the trailing slash on $ud to ensure $target is a subdir of $ud.  However
    # if $target eq $ud, we also need a trailing slash on $target for the comparision to
    # be successful
    fail ("debian directory in $pkg is an unsafe symlink!") unless "$target/" =~ m,^$ud/,;
}

# Copy the whole debian directory
copy_dir ("$dir/unpacked/debian/", "$dir/debfiles")
    or fail("cannot copy unpacked/debian to debfiles: $!");

}

collect (@ARGV) if $0 =~ m,(?:^|/)debfiles$,;

1;

# Local Variables:
# indent-tabs-mode: nil
# cperl-indent-level: 4
# End:
# vim: syntax=perl sw=4 sts=4 sr et
