#!/usr/bin/perl -w
# debian-readme -- lintian collector script

# Copyright (C) 1998 Richard Braakman
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, you can find it on the World Wide
# Web at http://www.gnu.org/copyleft/gpl.html, or write to the Free
# Software Foundation, Inc., 59 Temple Place - Suite 330, Boston,
# MA 02111-1307, USA.

use strict;

($#ARGV == 1) or fail("syntax: debian-readme <pkg> <type>");
my $pkg = shift;
my $type = shift;

-f "fields/package" or fail("debian-readme invoked in wrong directory");

unlink("README.Debian");

# Pick the first of these files that exists.
my @readmes = ("unpacked/usr/share/doc/$pkg/README.Debian.gz",
	    "unpacked/usr/share/doc/$pkg/README.Debian",
	    "unpacked/usr/share/doc/$pkg/README.debian.gz",
	    "unpacked/usr/share/doc/$pkg/README.debian",
        "unpacked/usr/doc/$pkg/README.Debian.gz",
	    "unpacked/usr/doc/$pkg/README.Debian",
	    "unpacked/usr/doc/$pkg/README.debian.gz",
	    "unpacked/usr/doc/$pkg/README.debian");

my $file;
for (@readmes) {
    if (-f $_) {
	$file = $_;
	last;
    }
}

if (not defined $file) {
    # no README found
    open(DUMMY, ">README.Debian");
    close(DUMMY);
} elsif ($file =~ m/\.gz$/) {
    use lib "$ENV{'LINTIAN_ROOT'}/lib";
    use Pipeline;

    pipeline((sub { exec 'gzip', '-dc', $file }), "README.Debian") == 0
	or fail("error in gzip");
} else {
    link($file, "README.Debian")
	or fail("cannot link $file to README.Debian: $!");
}

exit 0;

# -----------------------------------

sub fail {
    if ($_[0]) {
        print STDERR "internal error: $_[0]\n";
    } elsif ($!) {
        print STDERR "internal error: $!\n";
    } else {
        print STDERR "internal error.\n";
    }
    exit 1;
}
