#!/usr/bin/perl -w
# doc-base-files -- lintian collector script

# Copyright (C) 1998 Richard Braakman
# Copyright (C) 2001 Josip Rodin
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, you can find it on the World Wide
# Web at http://www.gnu.org/copyleft/gpl.html, or write to the Free
# Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
# MA 02110-1301, USA.

package Lintian::coll::doc_base_files;

use strict;
use warnings;
use autodie;

use lib "$ENV{'LINTIAN_ROOT'}/lib";
use Lintian::Util qw(copy_dir delete_dir fail is_ancestor_of);

sub collect {
    my ($pkg, $type, $dir) = @_;

    if (-e "$dir/doc-base") {
        delete_dir("$dir/doc-base")
          or fail('cannot rm old doc-base directory');
    }

    # If we are asked to only remove the files stop right here
    if ($type =~ m/^remove-/) {
        return;
    }

    if (-d "$dir/unpacked/usr/share/doc-base") {
        if (
            !is_ancestor_of(
                "$dir/unpacked", "$dir/unpacked/usr/share/doc-base"
            )
          ) {
            # Unsafe
            return;
        }
        copy_dir("$dir/unpacked/usr/share/doc-base", "$dir/doc-base")
          or fail('cannot copy directory unpacked/usr/share/doc-base');
    }

    return;
}

collect(@ARGV) if $0 =~ m,(?:^|/)doc-base-files$,;

1;

# Local Variables:
# indent-tabs-mode: nil
# cperl-indent-level: 4
# End:
# vim: syntax=perl sw=4 sts=4 sr et
