#!/usr/bin/perl -w
# file-info -- lintian collection script

# Copyright (C) 1998 Richard Braakman
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, you can find it on the World Wide
# Web at http://www.gnu.org/copyleft/gpl.html, or write to the Free
# Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
# MA 02110-1301, USA.

use strict;

use FileHandle;
use lib "$ENV{'LINTIAN_ROOT'}/lib";
use Util;
use Lintian::Command qw(spawn reap);

($#ARGV == 1) or fail("syntax: file-info <pkg> <type>");
my $pkg = shift;
my $type = shift;

-f "fields/package" or fail("file-info invoked in wrong directory");

unlink("file-info");
chdir("unpacked")
    or fail("cannot chdir to unpacked directory: $!");


my %opts = ( pipe_in => FileHandle->new,
	     out => '../file-info',
	     fail => 'error' );
spawn(\%opts, ['xargs', '-0r', 'file']);
open(INDEX, '<', "../index")
    or fail("cannot open index file: $!");
while (<INDEX>) {
    chop;
    $_ = (split(" ", $_, 6))[5];
    s/ link to .*//;
    s/ -> .*//;
    s/(\G|[^\\](?:\\\\)*)\\(\d{3})/"$1" . chr(oct $2)/ge;
    s/\\\\/\\/;
    printf {$opts{pipe_in}} "%s\0", $_;
}
close(INDEX);

close $opts{pipe_in};
reap(\%opts);
