#!/usr/bin/perl -w
# menu-files -- lintian collector script

# Copyright (C) 1998 Richard Braakman
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, you can find it on the World Wide
# Web at http://www.gnu.org/copyleft/gpl.html, or write to the Free
# Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
# MA 02110-1301, USA.

use strict;

($#ARGV == 1) or fail("syntax: menu-files <pkg> <type>");
my $pkg = shift;
my $type = shift;

-f "fields/package" or fail("menu-files invoked in wrong directory");

use lib "$ENV{'LINTIAN_ROOT'}/lib";
use Util;

if (-e "menu") {
    delete_dir('menu')
	or fail("cannot rm old menu directory");
}

mkdir("menu", 0777) or fail("cannot mkdir menu: $!");

if (-d "unpacked/usr/lib/menu") {    
     copy_dir('unpacked/usr/lib/menu', 'menu/lib')
	or fail("cannot copy unpacked/usr/lib/menu/ directory");
} else {
    # no menu directory
    mkdir("menu/lib", 0777) or fail("cannot mkdir menu/lib: $!");
}

if (-d "unpacked/usr/share/menu") {    
    copy_dir('unpacked/usr/share/menu', 'menu/share')
	or fail("cannot copy unpacked/usr/share/menu directory");
} else {
    # no menu directory
    mkdir("menu/share", 0777) or fail("cannot mkdir menu/share: $!");
}
