#!/usr/bin/perl -w
# menu-files -- lintian collector script

# Copyright (C) 1998 Richard Braakman
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, you can find it on the World Wide
# Web at http://www.gnu.org/copyleft/gpl.html, or write to the Free
# Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
# MA 02110-1301, USA.

use strict;

($#ARGV == 1) or fail("syntax: menu-files <pkg> <type>");
my $pkg = shift;
my $type = shift;

-f "fields/package" or fail("menu-files invoked in wrong directory");

BEGIN { push @INC, "$ENV{LINTIAN_ROOT}/checks" if defined $ENV{LINTIAN_ROOT}; }
use Pipeline;

if (-e "menu") {
    spawn('rm', '-rf', 'menu') == 0
	or fail("cannot rm old menu directory");
}

mkdir("menu", 0777) or fail("cannot mkdir menu: $!");

if (-d "unpacked/usr/lib/menu") {
    spawn('cp', '-a', 'unpacked/usr/lib/menu', 'menu/lib') == 0
	or fail("cannot copy unpacked/usr/lib/menu/ directory");
} else {
    # no menu directory
    mkdir("menu/lib", 0777) or fail("cannot mkdir menu/lib: $!");
}

if (-d "unpacked/usr/share/menu") {
    spawn('cp', '-a', 'unpacked/usr/share/menu', 'menu/share') == 0
	or fail("cannot copy unpacked/usr/share/menu directory");
} else {
    # no menu directory
    mkdir("menu/share", 0777) or fail("cannot mkdir menu/share: $!");
}


exit 0;

# -----------------------------------

sub fail {
    if ($_[0]) {
        print STDERR "internal error: $_[0]\n";
    } elsif ($!) {
        print STDERR "internal error: $!\n";
    } else {
        print STDERR "internal error.\n";
    }
    exit 1;
}
