#!/usr/bin/perl -w
# menu-files -- lintian collector script

# Copyright (C) 1998 Richard Braakman
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, you can find it on the World Wide
# Web at http://www.gnu.org/copyleft/gpl.html, or write to the Free
# Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
# MA 02110-1301, USA.

use strict;

($#ARGV == 1) or fail("syntax: menu-files <pkg> <type>");
my $pkg = shift;
my $type = shift;

-f "fields/package" or fail("menu-files invoked in wrong directory");

use lib "$ENV{'LINTIAN_ROOT'}/lib";
use Util;

if (-e "menu") {
    delete_dir('menu')
	or fail("cannot rm old menu directory");
}

mkdir("menu", 0777) or fail("cannot mkdir menu: $!");

my %dirs;
$dirs{'share'}   = 'usr/share/menu';
$dirs{'lib'}     = 'usr/lib/menu';
$dirs{'methods'} = 'etc/menu-methods';

while (my ($shortn, $path) = each %dirs) {
    if (-d "unpacked/$path") {
        if (!is_ancestor_of("unpacked", "unpacked/$path")) {
            # Unsafe, skip
            mkdir ("menu/$shortn", 0777) or fail ("cannot mkdir menu/$shortn: $!");
            next;
        }
	 copy_dir("unpacked/$path", "menu/$shortn")
	    or fail("cannot copy unpacked/$path/ directory");
    } else {
	# no menu directory
	mkdir("menu/$shortn", 0777) or fail("cannot mkdir menu/$shortn: $!");
    }
}
