#!/bin/sh -e
# strings -- lintian collection script

# Copyright (C) 2009 Raphael Geissert <atomo64@gmail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, you can find it on the World Wide
# Web at http://www.gnu.org/copyleft/gpl.html, or write to the Free
# Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
# MA 02110-1301, USA.

[ $# -eq 2 ] || {
    echo "Syntax: strings <pkg> <type>"
    exit 1
}

[ ! -f elf-index ] || rm -f elf-index
exec >elf-index

for bin in $(sed -rn 's/\x00\s+[^,]*\bELF\b.+$//g;T;p' file-info); do
    echo "$bin"
    case $bin in
      /usr/lib/debug/*)
        ;;
      *)
        mkdir -p "strings/$(dirname "$bin")"
        strings "unpacked/$bin" > "strings/$bin"
        ;;
    esac
done
