#!/usr/bin/perl -w

### BEGIN INIT INFO
# Provides:          init.d-general-interpreter-in-usr-dir
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

printf "start status stop reload restart force-reload\n";

