Tag: helper-templates-in-copyright
Severity: error
Check: debian/copyright
Explanation: The /usr/share/doc/*pkg*/copyright file still contains
 template markers from a packaging helper. Please fill in the actual
 license, upstream copyright holders, and download information about the
 package and remove any remaining templates generated by the packaging
 helper.
