Tag: pod-conversion-message
Severity: warning
Check: documentation/manual
Renamed-From: manpage-has-errors-from-pod2man
Explanation: A manual page contains a section <tt>POD ERRORS</tt>. This tag show
 the contents.
 .
 The section was generated by <tt>pod2man</tt>. It shows any errors that
 were found in the <tt>POD</tt> documentation when the page was generated.
