Tag: pod-conversion-message
Severity: warning
Check: documentation/manual
Renamed-From: manpage-has-errors-from-pod2man
Explanation: A manual page contains a section <code>POD ERRORS</code>. This tag show
 the contents.
 .
 The section was generated by <code>pod2man</code>. It shows any errors that
 were found in the <code>POD</code> documentation when the page was generated.
