Tag: file-contains-fixme-placeholder
Severity: info
Check: dh-make
Explanation: This file appears to be incomplete or insufficiently modified as it
 contains a "FIXME" placeholder text. These can often be generated by
 package generation tools such as dh&lowbar;make or npm2deb.
 .
 Please double-check the file and replace the placeholder with the required
 command or information.
