#!/bin/sh

set -e

if [ "$1" = "-j" ] ; then
    NUMJOBS="$2"
    test "$NUMJOBS" -gt 0 || (
        echo "$NUMJOBS is not an integer greater than 0" >&2 && exit 1)
    PARALLEL_ARGS="-j $NUMJOBS"
    shift
    shift
fi

if [ "$1" = "-t" ] ; then
    TAG=yes
fi

LANG="en_US.UTF-8"
LC_COLLATE="C"
LINTIAN_ROOT=""
LOCPATH="$(pwd)/debian/test.locale"

export LANG
export LC_COLLCATE
export LINTIAN_ROOT
export LOCPATH

fail(){
    echo "$1" >&2
    exit 1
}

if [ ! -e "$LOCPATH"/en_US.UTF-8 ] ; then
    echo "Generating en_US.UTF-8 locale for the test suite"
    mkdir -p "$LOCPATH"
    localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias \
        --quiet "$LOCPATH"/en_US.UTF-8 || fail "Locale generation failed"
fi

t/runtests -k $PARALLEL_ARGS t debian/tests "$@"
if [ "$TAG" = "" ] ; then
    testset/runtests -k testset debian/tests "$@"
fi
