#!/bin/sh

set -e

### BEGIN INIT INFO
# Provides: init.d-lsb-headers-remote
# Required-Start: $local_fs
# Required-Stop:
# Should-Stop: $remote_fs
# Default-Start: 2 3 4 5
# Default-Stop:
# Short-Description: Do nothing at all
# Description: The short description pretty much covers it.
### END INIT INFO

. /lib/lsb/init-functions
. /usr/share/foo/lib.sh

case "$1" in
    start|stop|force-reload|restart|status|*)
	echo hello world!
    ;;
esac
