#!/bin/sh

set +e

# delete Lintian tainted warning until #921112 is resolved
WITHOUT=$(fgrep -v "warning: tainted binary package 'control-field-traversal-4', skipping" "$2")
echo "$WITHOUT" > "$2"

# create calibrated tags
cp -p "$1" "$3"
