#!/bin/sh

# Good
echo $(py3versions -r)
echo $(py3versions -vr)
echo $(py3versions --requested)
echo $(py3versions --verbose --requested)

# Bad
echo $(py3versions -s)
echo $(py3versions -vs)
echo $(py3versions --supported)
echo $(py3versions --verbose --supported)

