#!/usr/bin/perl -w
# standards-version -- lintian check script

# Copyright (C) 1998 Christian Schwarz and Richard Braakman
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, you can find it on the World Wide
# Web at http://www.gnu.org/copyleft/gpl.html, or write to the Free
# Software Foundation, Inc., 59 Temple Place - Suite 330, Boston,
# MA 02111-1307, USA.

use strict;

my %valid_standard = (
		   '3.6.1', 1,
		   '3.6.0', 1,
		   '3.5.10', 2,
		   '3.5.9', 2,
		   '3.5.8', 2,
		   '3.5.7', 3,
		   '3.5.6', 3,
		   '3.5.5', 3,
		   '3.5.4', 3,
		   '3.5.3', 3,
		   '3.5.2', 3,
		   '3.5.1', 3,
		   '3.5.0', 3,
                   '3.2.1', 3,
                   '3.2.0', 3,
		   '3.1.1', 3,
		   '3.1.0', 3,
		   '3.0.1', 3,
		   '3.0.0', 3,
		   '2.5.1', 3,
		   '2.5.0', 3,
		   '2.4.1', 3,
		   '2.4.0', 3,
		   '2.3.0', 3,
		   '2.2.0', 3,
		   '2.1.3', 3,
		   '2.1.2', 3,
		   '2.1.1', 3,
		   '2.1.0', 3,
		   '2.0.1', 3,
		   '2.0.0', 3,
		   '0.2.1', 3,
		   '0.2.0', 3,
		  );

# version lintian is programmed for. ($valid_standard[0]?)
my $MAJOR = 3;
my $MINOR = 6;
my $PATCH = 1;

($#ARGV == 1) or fail("syntax: standards-version <pkg> <type>");
my $pkg = shift;
my $type = shift;

unless ( -d "fields" ) {
  fail("fields/ directory missing in lintian laboratory");
};

my $std = "fields/standards-version";
# Standards-Version?
if (not -f $std) {
    print "E: $pkg $type: no-standards-version-field\n";
    exit 0;
}

open(IN,$std) or fail("cannot open $std for reading: $!");
chop($_ = <IN>);
close(IN);

unless (m/^\s*(\d+\.\d+\.\d+)(?:\.\d+)?\s*$/) {
    # invalid standard
    print "E: $pkg $type: invalid-standards-version $_\n";
    exit 0;
}

my $stdver = $1;
my ($major, $minor, $patch) = $stdver =~ m/^(\d+)\.(\d+)\.(\d+)/;

if (not exists $valid_standard{$stdver}) {
    # unknown standard.  perhaps newer?
    if (($major > $MAJOR) or
	($major == $MAJOR and $minor > $MINOR) or
	($major == $MAJOR and $minor == $MINOR and $patch > $PATCH)) {
	print "W: $pkg $type: newer-standards-version $_\n";
    } else {
	# invalid standard
	print "E: $pkg $type: invalid-standards-version $_\n";
    }
} elsif ($valid_standard{$stdver} == 2) {
    # old standard
    print "W: $pkg $type: out-of-date-standards-version $_\n";
} elsif ($valid_standard{$stdver} == 3) {
    # OK, now this is ancient.
    print "W: $pkg $type: ancient-standards-version $_\n";
} else { # looks valid ......
    if (($major == 3 and $minor == 0) or $major < 3) {
	if (-f "fields/build-depends" or
	    -f "fields/build-depends-indep" or
	    -f "fields/build-conflicts" or
	    -f "fields/build-conflicts-indep") {
	    print "E: $pkg $type: package-declares-source-relation-but-has-older-standards-version $_ < 3.1.0\n";
	}
    }
}

exit 0;

# -----------------------------------

sub fail {
  if ($_[0]) {
    warn "internal error: $_[0]\n";
  } elsif ($!) {
    warn "internal error: $!\n";
  } else {
    warn "internal error.\n";
  }
  exit 1;
}
