Tag: generated-file
Severity: classification
Check: files/generated
Explanation: This file contains a common marker for generated files.
 .
 Some examples are:
 .
 - <code>DO NOT EDIT BY HAND</code>
 - <code>file was autogenerated</code>
 .
 In general, Debian likes to ship only true source files. Please consider
 asking upstream to generate the file during the build process instead.
