#!/bin/sh

set -e

DIR="$1"
mkfifo            "$DIR/debian/tests/fifo"
ln -s self        "$DIR/debian/tests/self"
ln -s self2       "$DIR/debian/tests/self2"
ln -s self2       "$DIR/debian/tests/self1"
ln -s nonexistent "$DIR/debian/tests/broken"
ln -s fifo        "$DIR/debian/tests/lfifo"
ln -s test-1      "$DIR/debian/tests/working"
