#!/bin/sh

set -e

. /lib/lsb/init-functions

### BEGIN INIT INFO
# Provides:          systemd-missing-services-without-rcs
# Required-Start:
# Required-Stop:
# Default-Start:     S 2 3 4 5
# Default-Stop:
# Short-Description: Do nothing at all
# Description: The short description pretty much covers it.
### END INIT INFO

case "$1" in
    start|stop|force-reload|restart|status|*)
	echo hello world!
    ;;
esac
