#!/bin/sh

set -e

### BEGIN INIT INFO
# Provides: init.d-lsb-headers-virtual
# Required-Start: $local_fs $something_that_doesnt_exist
# Should-Start: $something_we_might_not_ship
# Required-Stop: $all
# Default-Start: 2 3 4 5
# Default-Stop:
# Short-Description: Just a test script
# Description: The short description pretty much covers it.
### END INIT INFO

. /lib/lsb/init-functions

case "$1" in
    start|stop|force-reload|restart|status|*)
	echo hello world
    ;;
esac
