#!/bin/sh

set -e

DIR="$1"
NAME="changes-upstream-signature-missing"
VERSION="1.0"

# Check all components
cp ${DIR}/../${NAME}_${VERSION}.orig.tar.gz ${DIR}/../${NAME}_${VERSION}.orig-component.tar.gz

# Don't emit if we have a signature
cp ${DIR}/../${NAME}_${VERSION}.orig.tar.gz ${DIR}/../${NAME}_${VERSION}.orig-signed.tar.gz
touch ${DIR}/../${NAME}_${VERSION}.orig-signed.tar.gz.asc

# Don't emit if we have .tar.asc (NB. not a .tar.gz.asc)
cp ${DIR}/../${NAME}_${VERSION}.orig.tar.gz ${DIR}/../${NAME}_${VERSION}.orig-noext.tar.gz
touch ${DIR}/../${NAME}_${VERSION}.orig-noext.tar.gz.asc
